# Generated by Django 5.1.4 on 2024-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
